import { NgModule } from "@angular/core";
import { CommonModule } from "@angular/common";
import { Ng2SmartTableModule } from "ng2-smart-table";
import {
  NbLayoutModule,
  NbSidebarModule,
  NbSidebarService,
  NbCardModule,
  NbInputModule,
  NbButtonModule,
  NbTabsetModule,
  NbDatepickerModule,
  NbNativeDateService,
  NbDatepickerAdapter,
  NbDatepickerDirective,
  NbDateService,
  NbDatepicker,
  NbRadioModule,
  NbSelectModule,
  NbActionsModule,
  NbCheckboxComponent,
  NbStepperModule,
  NbAccordionModule,
  NbMenuModule,
  NbPopoverModule,
  NbContextMenuModule,
  NbToastrModule,
  NbTooltipModule,
  NbWindowModule,
  NbSearchModule,
  NbUserModule,
  NbSpinnerModule,
  NbProgressBarModule,
  NbBadgeModule,
  NbCalendarModule,
  NbCalendarRangeModule,
  NbListModule,
  NbDialogModule
} from "@nebular/theme";
import { NbDateFnsDateModule, NbDateFnsDateService } from "@nebular/date-fns";
import { NbMomentDateModule, NbMomentDateService } from "@nebular/moment";
import { FormsModule, ReactiveFormsModule } from "@angular/forms";
import { BrowserAnimationsModule } from "@angular/platform-browser/animations";
import { MaterialModule } from "./material.module";
@NgModule({
  declarations: [],
  imports: [
    CommonModule,
    NbLayoutModule,
    NbSidebarModule,
    NbCardModule,
    NbInputModule,
    NbButtonModule,
    NbTabsetModule,
    Ng2SmartTableModule,
    NbDatepickerModule,
    NbRadioModule,
    NbSelectModule,
    NbActionsModule,
    // NbDateFnsDateModule,
    // NbMomentDateModule
    NbActionsModule,

    NbSelectModule,
    NbStepperModule,
    NbAccordionModule,
    NbMenuModule,
    NbRadioModule,
    NbDatepickerModule,
    NbPopoverModule,
    NbContextMenuModule,
    NbToastrModule,
    NbTooltipModule,
    NbWindowModule,
    NbSearchModule,
    NbUserModule,
    NbSpinnerModule,
    NbProgressBarModule,
    NbBadgeModule,
    NbCalendarModule,
    NbCalendarRangeModule,
    NbListModule,
    NbDialogModule.forRoot(),
    FormsModule,
    ReactiveFormsModule,
    BrowserAnimationsModule,
    MaterialModule
  ],
  exports: [
    CommonModule,
    NbLayoutModule,
    NbSidebarModule,
    NbCardModule,
    NbInputModule,
    NbButtonModule,
    NbTabsetModule,
    Ng2SmartTableModule,
    NbDatepickerModule,
    NbRadioModule,
    NbSelectModule,
    NbActionsModule,
    // NbMomentDateModule
    // NbDateFnsDateModule,
    NbActionsModule,
    NbSelectModule,
    NbStepperModule,
    NbAccordionModule,
    NbMenuModule,
    NbRadioModule,
    NbDatepickerModule,
    NbPopoverModule,
    NbContextMenuModule,
    NbToastrModule,
    NbTooltipModule,
    NbWindowModule,
    NbSearchModule,
    NbUserModule,
    NbSpinnerModule,
    NbProgressBarModule,
    NbBadgeModule,
    NbCalendarModule,
    NbListModule,
    NbDialogModule,
    FormsModule,
    ReactiveFormsModule,
    MaterialModule
  ],
  providers: [NbSidebarService]
})
export class NebularModule {}
