import { NgModule } from "@angular/core";
import { CommonModule } from "@angular/common";
import { Ng2SmartTableModule } from "ng2-smart-table";
import {
  NbLayoutModule,
  NbSidebarModule,
  NbSidebarService,
  NbCardModule,
  NbInputModule,
  NbButtonModule,
  NbTabsetModule,
  NbActionsModule,
  NbSelectModule,
  NbCheckboxComponent,
  NbStepperModule,
  NbAccordionModule,
  NbMenuModule,
  NbRadioModule,
  NbDatepickerModule,
  NbPopoverModule,
  NbContextMenuModule,
  NbToastrModule,
  NbTooltipModule,
  NbWindowModule,
  NbSearchModule,
  NbUserModule,
  NbSpinnerModule,
  NbProgressBarModule,
  NbBadgeModule,
  NbCalendarModule,
  NbCalendarRangeModule,
  NbListModule,
  NbDialogModule
} from "@nebular/theme";

@NgModule({
  declarations: [],
  imports: [
    CommonModule,
    NbLayoutModule,
    NbSidebarModule,
    NbCardModule,
    NbInputModule,
    NbButtonModule,
    NbTabsetModule,
    Ng2SmartTableModule,
    NbActionsModule,

    NbSelectModule,
    NbStepperModule,
    NbAccordionModule,
    NbMenuModule,
    NbRadioModule,
    NbDatepickerModule,
    NbPopoverModule,
    NbContextMenuModule,
    NbToastrModule,
    NbTooltipModule,
    NbWindowModule,
    NbSearchModule,
    NbUserModule,
    NbSpinnerModule,
    NbProgressBarModule,
    NbBadgeModule,
    NbCalendarModule,
    NbCalendarRangeModule,
    NbListModule,
    NbDialogModule.forRoot()
  ],
  exports: [
    CommonModule,
    NbLayoutModule,
    NbSidebarModule,
    NbCardModule,
    NbInputModule,
    NbButtonModule,
    NbTabsetModule,
    Ng2SmartTableModule,
    NbActionsModule,
    NbSelectModule,
    NbStepperModule,
    NbAccordionModule,
    NbMenuModule,
    NbRadioModule,
    NbDatepickerModule,
    NbPopoverModule,
    NbContextMenuModule,
    NbToastrModule,
    NbTooltipModule,
    NbWindowModule,
    NbSearchModule,
    NbUserModule,
    NbSpinnerModule,
    NbProgressBarModule,
    NbBadgeModule,
    NbCalendarModule,
    NbListModule,
    NbDialogModule
  ],
  providers: [NbSidebarService]
})
export class NebularModule {}
